### ISSUE TITLE
Package seems to have disapeared from NPM

### ISSUE THREAD

**Issue by eXigentCoder** [n3ps/json-schema-to-jsdoc#1]
Hey there, just wanted to let you know that your library doesn't seem to appear on NPM (https://www.npmjs.com/search?q=json-schema-to-jsdoc).

I have installed directly from github for now using the command `npm install git+https://github.com/n3ps/json-schema-to-jsdoc.git`

**Comment by n3ps** [comment]
I haven't publish it (yet) because at the that time I wanted to add some more features but got caught with other priorities and never got around to doing it.

**Comment by n3ps** [comment]
Now on npm: https://www.npmjs.com/package/json-schema-to-jsdoc
