### ISSUE TITLE
Breaking changes or option additions?

### ISSUE THREAD

**Issue by brettz9** [n3ps/json-schema-to-jsdoc#6]
Hi,

Now that existing behavior is fully tested, I'm wondering whether you are open to some breaking changes or if you only may want the following as config changes:

- [x] 1. Avoid auto-adding "Represents a". If the schema doesn't have one, it should be ok to have resulting jsdoc without a description.
- [x] 2. When auto-adding "Represents a", use `schema.title` instead of `schema.id`. `id` was only a standard property [in an early draft](https://tools.ietf.org/html/draft-handrews-json-schema-02#page-73), and its replacement `$id` expects a [URI](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-8.2.2). For short plain text, one can use [`title`](http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.9.1). I presume this is what was intended here.
- [x] 3. Build a [`@typedef`](https://jsdoc.app/tags-typedef.html) element instead of `@name`. `@name` is used when you are forcing surrounding code to treat an item with that tag. But `@typedef` is intended for defining types. I'm not sure if people have use cases for `@name`, but I think in any case `@typedef` would be a better default, and at least optional.
    - [x] 1. The built `@typedef` could rely on the schema `type` for its type portion (and the `title` for its name), though user config might override (e.g., I like to use "PlainObject" instead of "object" to denote cases where the object is known not to need a special type).
- [x] 4. Avoid building trailing spaces:
    - [x] 1. After `@name` when there is no `schema.title`. (A test should in any case be added for when one is present.)
    - [x] 2. Avoid extra trailing space
    - [x] 3. Option to avoid *any* trailing space and `-` when there is no `schema.description`
- [x] 5. Provide an option for descriptions not to add a `-` at all as [some styles](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/.README/rules/require-hyphen-before-param-description.md) do not use a hyphen.
- [x] 6. Ability to disable the capitalized auto-typing of untyped properties (the curly bracketed type could either be omitted or left empty).
- [x] 7. Allow controlling the indent; by default I think it should be one space as in [the docs](https://jsdoc.app/about-getting-started.html#adding-documentation-comments-to-your-code) instead of 2 spaces.
- [x] 8. Use `schema.default` for e.g., `@param {MyType} [someName=aDefaultValue]`.
- [x] 9. For nested properties, avoid prefixing with `.`, but use the approach documented with [`@property`](https://jsdoc.app/tags-property.html), i.e., of having the ancestors with their own document, and then the descendants repeating the ancestor info joined by dots e.g., `@property {object} grandparent` then `@property {object} grandparent.parent` then `@property {someType} grandparent.parent.child`.
- [ ] 10. Auto-add line breaks and asterisks if the description would cause the line length to go past a certain point, e.g., to build:
```js
 /**
  * @property {string} [aStringProp] - This is a very, very, very, very, very, very, very, very
  * very, very, very long description.
  */
```
- [x] 11. Also supporting arrays whose `items` are checked instead of `properties`.

**Comment by brettz9** [comment]
Btw, even if you can reply gradually one item at a time, that'd be helpful so I could see about making PRs to support the option/new default/replacement.

**Comment by n3ps** [comment]
Thanks for the suggestions. I haven't kept up with the latest JSON Schema specs. If some properties have changed I agree with updating them.

1-2. I originally created this for use with entities, hence the "Represents..." text
3. Sure. Can't recall why @name was chosen.
4. Also can't recall why the trailing spaces. Probably due to some JSDoc tool I used as reference
5. Interesting, can be in options
6. What's an example?
7. Sure, probably due to an old reference again
8. Sure
9. Again this stems from original intention for use with entities. Can be options.
10. Does JSDoc have a stance on this? If not what's a reasonable default, 80?

**Comment by brettz9** [comment]
Re: no. 6:

> Ability to disable the capitalized auto-typing of untyped properties (the curly bracketed type could either be omitted or left empty).

...I am referring to the behavior in the "Object with untyped property" test where `aNestedProp`, which has no type:

```js
properties: {
      anObjectProp: {
        type: 'object',
        properties: {
          aNestedProp: {
          },
          anotherNestedProp: {
            type: 'number'
          }
      }
  }
}
```

...is currently automatically given a type `ANestedProp` in the output:

```js
  * @property {ANestedProp} [.aNestedProp] - ${trailingSpace}
```

I'd like to add the option to have no `{ANestedProp}` auto-created there, and maybe not even an empty `{}`.

Re: no. 10 and a reasonable default width, yes, I think 80 chars. is a good one. Re: Jsdoc mentioning this, the only mention I see having to do with this is just this statement from https://jsdoc.app/plugins-markdown.html :

> it's normal for a JSDoc comment to be wrapped across multiple lines.

Though the `@description` tag (which is the explicit tag for a jsdoc description heading) doesn't have an example of multiline usage, the `@example tag` has an example where the asterisks are repeated per each line:

From https://jsdoc.app/tags-example.html

```js
/**
 * Solves equations of the form a * x = b
 * @example
 * // returns 2
 * globalNS.method1(5, 10);
 * @example
 * // returns 3
 * globalNS.method(5, 15);
 * @returns {Number} Returns the value of x for the equation.
 */
```
